# Generated by Django 2.2.4 on 2019-12-16 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_turno', models.BooleanField(choices=[(0, 'Fijo'), (1, 'Rotativo')])),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('duracion_horas', models.DecimalField(decimal_places=1, default=7.5, max_digits=4)),
                ('tipo_continuidad', models.BooleanField(choices=[(0, 'Temporal'), (1, 'Permanente')])),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_turnos', to='registration.Area')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['nombre', 'area'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTurnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_detalle', to='cargos.Cargo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_detalle', to='turnos.Turnos')),
            ],
        ),
    ]
