# Generated by Django 2.2.7 on 2019-11-29 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=13, null=True, verbose_name='Numero de Telefono')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('type_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_typeuser', to='registration.TypeUser', verbose_name='Tipo de usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__firstname'],
            },
        ),
    ]
