# Generated by Django 2.2.7 on 2019-12-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_area_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area_user',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='registration.Area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relacion_typeuser', to='registration.TypeUser', verbose_name='Tipo de usuario'),
        ),
    ]
