# Generated by Django 2.2.7 on 2019-12-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20191204_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='boos_user',
            new_name='boss_user',
        ),
    ]
