# Generated by Django 2.2.7 on 2019-12-05 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20191205_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='boss_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Jefe de area'),
        ),
    ]
